### ISSUE TITLE
アイコンをアウトラインアイコンに変更

### ISSUE THREAD

**Issue by Robot-Inventor** [Robot-Inventor/spam-tweets-compressor#483]
## アイコンフォントのURL

```
https://fonts.googleapis.com/css?family=Material+Icons&display=block => https://fonts.googleapis.com/css?family=Material+Icons+Outlined&display=block
```

## CSS変数

```css
:root {
    /* 追加 */
    --mdc-icon-font: "Material Icons Outlined"
}
```
