### ISSUE TITLE
詳細設定のメニューに改行が入らないようにする

### ISSUE THREAD

**Issue by Robot-Inventor** [Robot-Inventor/spam-tweets-compressor#505]
詳細設定のメニューの文字に改行が入ってしまって分かりにくくなっている。

![image](https://user-images.githubusercontent.com/50550561/140653032-b6ab4332-5c97-4e8b-9b76-11536edba814.png)

次のように指定することで、改行が入らないようにできる。

```css
mwc-drawer {
    --mdc-drawer-width: auto;
}
```

![image](https://user-images.githubusercontent.com/50550561/140653102-b82245e8-a299-493f-a8a9-c497f5bf4a89.png)
